/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "textTransform": "none"
    },
    "textarea": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "fontFamily": "RacingSansOne",
      "fontSize": 30,
      "letterSpacing": "0.025em"
    },
    "h2": {
      "fontFamily": "RacingSansOne",
      "fontSize": 24,
      "letterSpacing": "0.025em"
    },
    "h3": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h4": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h5": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "[hidden]": {
      "display": "none"
    },
    "font-racing": {
      "fontFamily": "RacingSansOne"
    },
    "font-inter": {
      "fontFamily": "Inter"
    },
    "container": {
      "width": "100%"
    },
    "container@0": {
      "maxWidth": 640
    },
    "container@1": {
      "maxWidth": 768
    },
    "container@2": {
      "maxWidth": 1024
    },
    "container@3": {
      "maxWidth": 1280
    },
    "container@4": {
      "maxWidth": 1536
    },
    "body-bold": {
      "fontFamily": "Inter",
      "fontSize": 16,
      "fontWeight": "700"
    },
    "card": {
      "borderTopLeftRadius": 24,
      "borderTopRightRadius": 24,
      "borderBottomRightRadius": 24,
      "borderBottomLeftRadius": 24,
      "backgroundColor": "rgb(255, 255, 255)",
      "paddingTop": 32,
      "paddingRight": 32,
      "paddingBottom": 32,
      "paddingLeft": 32
    },
    "tab-icon": {
      "alignItems": "center",
      "justifyContent": "center",
      "borderTopLeftRadius": 9999,
      "borderTopRightRadius": 9999,
      "borderBottomRightRadius": 9999,
      "borderBottomLeftRadius": 9999,
      "backgroundColor": "rgba(31, 41, 55, 1)",
      "width": 44,
      "height": 44
    },
    "tab-icon-active": {
      "backgroundColor": "rgba(37, 99, 235, 1)"
    },
    "absolute": {
      "position": "absolute"
    },
    "relative": {
      "position": "relative"
    },
    "inset-x-0": {
      "left": 0,
      "right": 0
    },
    "bottom-0": {
      "bottom": 0
    },
    "left-0": {
      "left": 0
    },
    "right-0": {
      "right": 0
    },
    "z-0": {
      "zIndex": 0
    },
    "z-20": {
      "zIndex": 20
    },
    "mx-auto": {
      "marginLeft": "auto",
      "marginRight": "auto"
    },
    "flex": {
      "display": "flex"
    },
    "hidden": {
      "display": "none"
    },
    "h-[52px]": {
      "height": 52
    },
    "h-[75px]": {
      "height": 75
    },
    "h-full": {
      "height": "100%"
    },
    "max-h-[70%]": {
      "maxHeight": "70%"
    },
    "max-h-[80%]": {
      "maxHeight": "80%"
    },
    "w-[85%]": {
      "width": "85%"
    },
    "w-[90%]": {
      "width": "90%"
    },
    "w-[95%]": {
      "width": "95%"
    },
    "w-full": {
      "width": "100%"
    },
    "min-w-[250px]": {
      "minWidth": 250
    },
    "max-w-[280px]": {
      "maxWidth": 280
    },
    "max-w-[320px]": {
      "maxWidth": 320
    },
    "flex-1": {
      "flexGrow": 1,
      "flexShrink": 1,
      "flexBasis": "0%"
    },
    "shrink": {
      "flexShrink": 1
    },
    "flex-row": {
      "flexDirection": "row"
    },
    "items-end": {
      "alignItems": "flex-end"
    },
    "items-center": {
      "alignItems": "center"
    },
    "justify-end": {
      "justifyContent": "flex-end"
    },
    "justify-center": {
      "justifyContent": "center"
    },
    "justify-between": {
      "justifyContent": "space-between"
    },
    "overflow-hidden": {
      "overflow": "hidden"
    },
    "truncate": {
      "overflow": "hidden"
    },
    "rounded": {
      "borderTopLeftRadius": "0.25rem",
      "borderTopRightRadius": "0.25rem",
      "borderBottomRightRadius": "0.25rem",
      "borderBottomLeftRadius": "0.25rem"
    },
    "rounded-[20px]": {
      "borderTopLeftRadius": 20,
      "borderTopRightRadius": 20,
      "borderBottomRightRadius": 20,
      "borderBottomLeftRadius": 20
    },
    "rounded-full": {
      "borderTopLeftRadius": 9999,
      "borderTopRightRadius": 9999,
      "borderBottomRightRadius": 9999,
      "borderBottomLeftRadius": 9999
    },
    "rounded-lg": {
      "borderTopLeftRadius": "0.5rem",
      "borderTopRightRadius": "0.5rem",
      "borderBottomRightRadius": "0.5rem",
      "borderBottomLeftRadius": "0.5rem"
    },
    "rounded-md": {
      "borderTopLeftRadius": "0.375rem",
      "borderTopRightRadius": "0.375rem",
      "borderBottomRightRadius": "0.375rem",
      "borderBottomLeftRadius": "0.375rem"
    },
    "rounded-xl": {
      "borderTopLeftRadius": "0.75rem",
      "borderTopRightRadius": "0.75rem",
      "borderBottomRightRadius": "0.75rem",
      "borderBottomLeftRadius": "0.75rem"
    },
    "rounded-t-xl": {
      "borderTopLeftRadius": "0.75rem",
      "borderTopRightRadius": "0.75rem"
    },
    "border": {
      "borderTopWidth": 1,
      "borderRightWidth": 1,
      "borderBottomWidth": 1,
      "borderLeftWidth": 1
    },
    "border-b": {
      "borderBottomWidth": 1
    },
    "border-t": {
      "borderTopWidth": 1
    },
    "border-[#00adb5]/20": {
      "borderTopColor": "rgba(0, 173, 181, 0.2)",
      "borderRightColor": "rgba(0, 173, 181, 0.2)",
      "borderBottomColor": "rgba(0, 173, 181, 0.2)",
      "borderLeftColor": "rgba(0, 173, 181, 0.2)"
    },
    "border-[#373792]": {
      "borderTopColor": "rgba(55, 55, 146, 1)",
      "borderRightColor": "rgba(55, 55, 146, 1)",
      "borderBottomColor": "rgba(55, 55, 146, 1)",
      "borderLeftColor": "rgba(55, 55, 146, 1)"
    },
    "border-[#ff4ccc]": {
      "borderTopColor": "rgba(255, 76, 204, 1)",
      "borderRightColor": "rgba(255, 76, 204, 1)",
      "borderBottomColor": "rgba(255, 76, 204, 1)",
      "borderLeftColor": "rgba(255, 76, 204, 1)"
    },
    "border-white/10": {
      "borderTopColor": "rgba(255, 255, 255, 0.1)",
      "borderRightColor": "rgba(255, 255, 255, 0.1)",
      "borderBottomColor": "rgba(255, 255, 255, 0.1)",
      "borderLeftColor": "rgba(255, 255, 255, 0.1)"
    },
    "border-white/5": {
      "borderTopColor": "rgba(255, 255, 255, 0.05)",
      "borderRightColor": "rgba(255, 255, 255, 0.05)",
      "borderBottomColor": "rgba(255, 255, 255, 0.05)",
      "borderLeftColor": "rgba(255, 255, 255, 0.05)"
    },
    "bg-[#00adb5]": {
      "backgroundColor": "rgba(0, 173, 181, 1)"
    },
    "bg-[#00adb5]/10": {
      "backgroundColor": "rgba(0, 173, 181, 0.1)"
    },
    "bg-[#0f062d]": {
      "backgroundColor": "rgba(15, 6, 45, 1)"
    },
    "bg-[#111]": {
      "backgroundColor": "rgba(17, 17, 17, 1)"
    },
    "bg-[#121212]": {
      "backgroundColor": "rgba(18, 18, 18, 1)"
    },
    "bg-[#150935]": {
      "backgroundColor": "rgba(21, 9, 53, 1)"
    },
    "bg-[#150935]/90": {
      "backgroundColor": "rgba(21, 9, 53, 0.9)"
    },
    "bg-[#1a0b0b]": {
      "backgroundColor": "rgba(26, 11, 11, 1)"
    },
    "bg-[#555]": {
      "backgroundColor": "rgba(85, 85, 85, 1)"
    },
    "bg-[#D9D9D9]": {
      "backgroundColor": "rgba(217, 217, 217, 1)"
    },
    "bg-[#ccc]": {
      "backgroundColor": "rgba(204, 204, 204, 1)"
    },
    "bg-[#ff4ccc]": {
      "backgroundColor": "rgba(255, 76, 204, 1)"
    },
    "bg-black": {
      "backgroundColor": "rgba(0, 0, 0, 1)"
    },
    "bg-black/50": {
      "backgroundColor": "rgba(0, 0, 0, 0.5)"
    },
    "bg-black/70": {
      "backgroundColor": "rgba(0, 0, 0, 0.7)"
    },
    "bg-gray-100": {
      "backgroundColor": "rgba(243, 244, 246, 1)"
    },
    "bg-gray-300": {
      "backgroundColor": "rgba(209, 213, 219, 1)"
    },
    "bg-gray-600/20": {
      "backgroundColor": "rgba(75, 85, 99, 0.2)"
    },
    "bg-green-600/20": {
      "backgroundColor": "rgba(22, 163, 74, 0.2)"
    },
    "bg-red-600/90": {
      "backgroundColor": "rgba(220, 38, 38, 0.9)"
    },
    "bg-white": {
      "backgroundColor": "rgba(255, 255, 255, 1)"
    },
    "bg-white/10": {
      "backgroundColor": "rgba(255, 255, 255, 0.1)"
    },
    "bg-white/5": {
      "backgroundColor": "rgba(255, 255, 255, 0.05)"
    },
    "p-[1px]": {
      "paddingTop": 1,
      "paddingRight": 1,
      "paddingBottom": 1,
      "paddingLeft": 1
    },
    "py-0": {
      "paddingTop": 0,
      "paddingBottom": 0
    },
    "text-center": {
      "textAlign": "center"
    },
    "font-magistral": {
      "fontFamily": "Magistral"
    },
    "font-magistralMedium": {
      "fontFamily": "MagistralMedium"
    },
    "font-proRacing": {
      "fontFamily": "ProRacing"
    },
    "font-proRacingSlant": {
      "fontFamily": "ProRacingSlant"
    },
    "text-2xl": {
      "fontSize": "1.5rem",
      "lineHeight": "2rem"
    },
    "text-3xl": {
      "fontSize": "1.875rem",
      "lineHeight": "2.25rem"
    },
    "text-4xl": {
      "fontSize": "2.25rem",
      "lineHeight": "2.5rem"
    },
    "text-[14px]": {
      "fontSize": 14
    },
    "text-[17px]": {
      "fontSize": 17
    },
    "text-[22px]": {
      "fontSize": 22
    },
    "text-[24px]": {
      "fontSize": 24
    },
    "text-[30px]": {
      "fontSize": 30
    },
    "text-[40px]": {
      "fontSize": 40
    },
    "text-base": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem"
    },
    "text-lg": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem"
    },
    "text-sm": {
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem"
    },
    "text-xl": {
      "fontSize": "1.25rem",
      "lineHeight": "1.75rem"
    },
    "text-xs": {
      "fontSize": "0.75rem",
      "lineHeight": "1rem"
    },
    "font-bold": {
      "fontWeight": "700"
    },
    "font-medium": {
      "fontWeight": "500"
    },
    "font-normal": {
      "fontWeight": "400"
    },
    "font-semibold": {
      "fontWeight": "600"
    },
    "uppercase": {
      "textTransform": "uppercase"
    },
    "capitalize": {
      "textTransform": "capitalize"
    },
    "italic": {
      "fontStyle": "italic"
    },
    "tracking-wide": {
      "letterSpacing": "0.025em"
    },
    "tracking-wider": {
      "letterSpacing": "0.05em"
    },
    "text-[#00adb5]": {
      "color": "rgba(0, 173, 181, 1)"
    },
    "text-[#FFFFFF]": {
      "color": "rgba(255, 255, 255, 1)"
    },
    "text-black": {
      "color": "rgba(0, 0, 0, 1)"
    },
    "text-gray-400": {
      "color": "rgba(156, 163, 175, 1)"
    },
    "text-gray-600": {
      "color": "rgba(75, 85, 99, 1)"
    },
    "text-gray-800": {
      "color": "rgba(31, 41, 55, 1)"
    },
    "text-green-400": {
      "color": "rgba(74, 222, 128, 1)"
    },
    "text-red-200": {
      "color": "rgba(254, 202, 202, 1)"
    },
    "text-red-500": {
      "color": "rgba(239, 68, 68, 1)"
    },
    "text-white": {
      "color": "rgba(255, 255, 255, 1)"
    },
    "text-white/60": {
      "color": "rgba(255, 255, 255, 0.6)"
    },
    "text-white/80": {
      "color": "rgba(255, 255, 255, 0.8)"
    },
    "text-white/90": {
      "color": "rgba(255, 255, 255, 0.9)"
    },
    "text-yellow-400": {
      "color": "rgba(250, 204, 21, 1)"
    },
    "underline": {
      "textDecorationLine": "underline"
    },
    "opacity-100": {
      "opacity": 1
    },
    "opacity-50": {
      "opacity": 0.5
    }
  },
  atRules: {
    "container": [[["media", "(min-width: 640px)"]], [["media", "(min-width: 768px)"]], [["media", "(min-width: 1024px)"]], [["media", "(min-width: 1280px)"]], [["media", "(min-width: 1536px)"]]]
  },
  topics: {
    "container": ["width"]
  }
});